name: Terraform Azure Deploy

on:
  workflow_dispatch:  # 👈 Déclenchement manuel uniquement

jobs:
  terraform:
    name: Terraform Init & Apply on Azure
    runs-on: ubuntu-latest

    env:
      TF_VAR_azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      TF_VAR_azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_azure_tenant_id: "297246f1-5c28-4f6f-88aa-8990cb7383b1"
      # TF_VAR_location: ${{ secrets.AZURE_LOCATION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
